#!/bin/bash

export EDITOR=vi

isExist(){ 
    type $1 &> /dev/null 
}
pathmunge () {
    case ":${PATH}:" in
        *:"$1":*)
            ;;
        *)
            if [ "$2" = "after" ] ; then
                PATH=$PATH:$1
            else
                PATH=$1:$PATH
            fi
    esac
}

_misc(){
    alias grpe="grep"
    alias gpre="grep"
    alias ap="ansible-playbook"
}

_docker(){
    if ( isExist docker-compose ) ; then
        alias dc="docker-compose"
    fi
}

_aws(){
    export PATH="${PATH}:${HOME}/.krew/bin"
    export AWS_ACCESS_KEY_ID=$( grep aws_access_key_id ~/.aws/credentials  | sed -e "s/aws_access_key_id = //" )
    export AWS_SECRET_ACCESS_KEY=$( grep aws_secret_access_key ~/.aws/credentials  | sed -e "s/aws_secret_access_key = //" )
    export AWS_REGION_CODE=$( grep region ~/.aws/config  | sed -e "s/region = //" )

    if ( isExist eksctl ) ; then
        complete -C  $( type -p aws_completer ) aws
        . <( eksctl completion  bash  )

        alias ec="eksctl"
         . <( eksctl completion  bash | sed -e 's/eksctl/ec/g' )
    fi
}

_kubernetes(){

    if ( isExist kubectl ) ; then
        . <( kubectl completion bash )

        alias k="kubectl"
        complete -o default -F __start_kubectl k

        alias kns="kubectl ns"
        alias kctx="kubectl ctx"

        if ( isExist kubecolor ) ; then
            alias k=kubecolor
            complete -o default -F __start_kubectl kubecolor
        fi
    fi

    if ( isExist kind ) ; then
        . <(kind completion bash )
    fi
    if ( isExist kustomize ) ; then
        . <(kustomize completion bash )
    fi
}
_openshift(){
    if ( isExist oc ) ; then
        . <(oc completion bash)
    fi
}
_azure(){
    export PATH=$PATH:~/bin
    source ~/lib/azure-cli/az.completion
}

_powerline() {
    function _update_ps1() {
        PS1="$(powerline-go -error $? -jobs $(jobs -p | wc -l) $PL_OPTS)"

        # Uncomment the following line to automatically clear errors after showing
        # them once. This not only clears the error for powerline-go, but also for
        # everything else you run in that shell. Don't enable this if you're not
        # sure this is what you want.

        set "?"
    }

    if ( isExist powerline-go ) ; then
        if [ "$TERM" != "linux" ] ; then
            PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
            PL_OPTS="-modules venv,user,host,cwd,git,root -theme gruvbox"
        fi
    fi
}

if [ -d /usr/local/bin ] ; then
    pathmunge /usr/local/bin after
fi
if [ -d ~/bin ] ; then
    pathmunge ~/bin after
fi

if [ -d ~/.local/bin ] ; then
    pathmunge ~/.local/bin after
fi

if [ -d ~/.krew/bin ] ; then
    pathmunge ~/.krew/bin after
fi
export PATH


